apiVersion: v1
kind: Route
metadata:
  name: mobile-simulator-service
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
spec:
  to:
    kind: Service
    name: mobile-simulator-service
